### PR TITLE
Anonymous votes feature + Migration + Basque i18n translations

### PR DESCRIPTION
**Pull request by urtzai**

### CODE REVIEW

**Comment by rolo** [comment]
Hi there. Thanks for this :)

One point - was there a reason for separating out the anonymous ratings into a separate model rather than allowing a null User on the existing one? That would intuitively be what I'd try to do first. Cheers.

**Comment by urtzai** [comment]
Hi! The reason was not to mess the main development. The user is required and I thought it was critical... But you are right, probably it is simpler to develop all in one.

**Comment by rolo** [comment]
Okay cool, well if you're happy to change and add another PR then we can take a look. Note the failing tests too, although suspect that will be easier to fix with the one model. Cheers.

**Comment by urtzai** [comment]
Nice! Ok I'll do. Cheers.

**Pull request closed without merging**
