### PR TITLE
add i18n support

### PR DESCRIPTION
**Pull request by ollb**

### CODE REVIEW

**Comment by ollb** [comment]
We are glad to find "django-star-ratings" app. Here a couple of pull requests.

The first adds support for translation.

**Comment by ollb** [comment]
Is CI broken ?

**Comment by jneves** [comment]
@ollb no, I actually suspect the failure is caused by your changes: on line 35 of star_ratings/views.py an error message is being sent to the DjangoJSONEncoder which can't handle the direct return of gettext (which returns a proxy object and not a string). One solution would be just to encode it with unicode() so it is a string that DjangoJSONEncoder knows how to deal with. I hope this helps.

**Comment by ollb** [comment]
@jneves ok thanks,  I used ugettext instead of ugettext_lazy (I didn't realize the ValidationError was serialized).

**Comment by jneves** [comment]
@ollb Merci beacoup!

**Pull request merged**
