### PR TITLE
Bugfix: Update widget_base.html 

### PR DESCRIPTION
**Pull request by spec45as**
Fixed bug with wrong Initial value of number of stars
percentage var. is decimal, but it should be int for correct loading with <style>

### CODE REVIEW

**Comment by jonashagstedt** [comment]
Could you show an example so we can replicate this.
I'm not sure I am reading your comment correctly but are you saying that decimal values are not valid for CSS percentages? (they are)

**Comment by spec45as** [comment]
Yes, i supposed that python output for css value was incorrect 
I am no longer sure, but it solved my problem - also, i  have checked my percentage var before creating html page - it was correct, so, i decided there is something wrong with html template part
My django ver is 1.9 and python is 3.5.1

**Comment by JuanmaNatal** [comment]
I had an issue here and I think it was because 'percentage' uses ',' for decimals (that's what appears to me when checking with the developer toolbar) when my codification uses '.'.
So to correct it, I did the following change:
<ul class="star-ratings-rating-foreground" style="width: {{ percentage }}%">
to:
<ul class="star-ratings-rating-foreground" style="width: {{ percentage|floatformat }}%">

**Comment by JuanmaNatal** [comment]
#71 

Have seen it was proposed to correct here later.

**Comment by radiac** [comment]
Thanks for the PR, sorry it took so long for us to deal with it!

**Pull request closed without merging**
